### ISSUE TITLE
java.lang.IllegalStateException: View with id 2131230844: razerdp.github.com.widget.PhotoContents#onMeasure() did not set the measured dimension by calling setMeasuredDimension()

### ISSUE THREAD

**Issue by 70kg** [razerdp/PhotoContents#3]
在这里 https://github.com/razerdp/PhotoContents/blob/master/lib/src/main/java/razerdp/github/com/widget/PhotoContents.java#L92  
需要调一下`setMeasuredDimension`

**Comment by razerdp** [comment]
@70kg 好的，谢谢，这个控件最近有收到反馈有几个地方有问题，我会一同解决掉

**Comment by razerdp** [comment]
已更新
